[package]
name = "Blaze"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "5.0.1"
disk-name = "=1.0.0"
open = "5.3.0"
rayon = "1.10.0"
ron = "0.8.1"
serde = { version = "1.0.210", features = ["serde_derive"] }
slint = "1.8.0"
